version: '3.8'

services:
  mysql:
    image: mysql:5.7
    ports:
      - 8195:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: yourpassword
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
      - ./.docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD
      interval: 5s
      retries: 10

  # PhpMyAdmin Service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5
    ports:
      - 8194:80
    environment:
      PMA_HOST: mysql
    depends_on:
      mysql:
        condition: service_healthy